spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/javelin?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  resources:
    add-mappings: true
security:
  basic:
    enabled: false
server:
  port: 8080
multipart:
  max-file-size: 3Mb
  max-request-size: 3Mb

